plugins {
  id 'java'
  id 'org.springframework.boot' version '3.3.5'
  id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.wcpe'
version = '0.1.0'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'
  testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

tasks.named('bootJar') {
  archiveFileName = 'margin-service-0.1.0.jar'
}

tasks.named('test') {
  useJUnitPlatform()
  systemProperty 'spring.profiles.active', 'test'
}
