import type { RateFeedOperationsView } from '../../lib/api/rateFeedOps';

export const rateFeedOperationsFixture: RateFeedOperationsView = {
  tenantContext: 'tenant-fixture',
  dependencyStatus: 'CONFIGURED_REFS_SUPPLIED',
  lastUpdatedRef: 'time-ref:rate-feed-ops-fixture-updated',
  feedHealth: {
    totalFeeds: 'count-ref:all-rate-feeds',
    healthy: 'count-ref:healthy-feeds',
    degraded: 'count-ref:degraded-feeds',
    failed: 'count-ref:failed-feeds',
    lastSuccessfulIngestRef: 'ingest-ref:last-successful-fixture',
    feeds: [
      {
        feedId: 'feed-ref:fixture-primary',
        feedName: 'Primary investor feed fixture',
        investorRef: 'investor-ref:configured-primary',
        lastRunRef: 'run-ref:feed-fixture-001',
        status: 'HEALTHY',
        freshnessRef: 'freshness-ref:backend-owned-current',
        rowCountRef: 'row-count-ref:backend-owned-total',
        blockerCountRef: 'blocker-count-ref:backend-owned-open',
        detailTargetRef: 'integration-workbench-ref:feed-fixture-001',
      },
      {
        feedId: 'feed-ref:fixture-secondary',
        feedName: 'Secondary investor feed fixture',
        investorRef: 'investor-ref:configured-secondary',
        lastRunRef: 'run-ref:feed-fixture-002',
        status: 'DEGRADED',
        freshnessRef: 'freshness-ref:backend-owned-stale',
        rowCountRef: 'row-count-ref:backend-owned-secondary',
        blockerCountRef: 'blocker-count-ref:backend-owned-secondary-open',
        detailTargetRef: 'integration-workbench-ref:feed-fixture-002',
      },
    ],
  },
  workflowSteps: [
    {
      stepId: 'INGEST',
      label: 'Ingest',
      status: 'COMPLETED',
      sourceBoundary: 'rate-feed-service:ingest-workflow-ref',
      auditRef: 'audit-ref:ingest-fixture',
      resultHashRef: 'result-hash-ref:ingest-fixture',
      inputRef: 'input-ref:investor-delivery-fixture',
      outputRef: 'output-ref:raw-feed-fixture',
      timingRef: 'timing-ref:ingest-fixture',
      logRefs: ['log-ref:ingest-fixture'],
      actionPermitted: false,
    },
    {
      stepId: 'VALIDATE',
      label: 'Validate',
      status: 'FAILED',
      sourceBoundary: 'rate-feed-service:validation-report-ref',
      auditRef: 'audit-ref:validate-fixture',
      resultHashRef: 'result-hash-ref:validate-fixture',
      inputRef: 'input-ref:raw-feed-fixture',
      outputRef: 'output-ref:blocker-report-fixture',
      timingRef: 'timing-ref:validate-fixture',
      errorRefs: ['error-ref:row-blockers-present'],
      logRefs: ['log-ref:validate-fixture'],
      actionPermitted: false,
    },
    {
      stepId: 'TRANSFORM',
      label: 'Transform',
      status: 'PENDING',
      sourceBoundary: 'rate-feed-service:transform-workflow-ref',
      auditRef: 'audit-ref:transform-pending',
      resultHashRef: 'result-hash-ref:transform-pending',
      actionPermitted: false,
    },
    {
      stepId: 'ENRICH',
      label: 'Enrich',
      status: 'PENDING',
      sourceBoundary: 'rate-feed-service:enrichment-workflow-ref',
      auditRef: 'audit-ref:enrich-pending',
      resultHashRef: 'result-hash-ref:enrich-pending',
      actionPermitted: false,
    },
    {
      stepId: 'PUBLISH',
      label: 'Publish',
      status: 'PENDING',
      sourceBoundary: 'pricing-service:grid-publication-ref',
      auditRef: 'audit-ref:publish-pending',
      resultHashRef: 'result-hash-ref:publish-pending',
      actionPermitted: false,
    },
    {
      stepId: 'VERIFY',
      label: 'Verify',
      status: 'SKIPPED',
      sourceBoundary: 'audit-replay-service:verification-ref',
      auditRef: 'audit-ref:verify-skipped',
      resultHashRef: 'result-hash-ref:verify-skipped',
      actionPermitted: false,
    },
  ],
  rowBlockers: [
    {
      rowRef: 'row-ref:feed-fixture-042',
      fieldName: 'noteRateRef',
      severity: 'BLOCKER',
      blockerCode: 'MISSING_RATE',
      sourceReference: 'source-ref:rate-feed-batch/row/42',
      resolutionState: 'OPEN',
      rowDataRefs: ['row-data-ref:fixture-042'],
      expectedRef: 'expected-ref:backend-required-rate-field',
      actualRef: 'actual-ref:source-value-missing',
      remediationRef: 'remediation-ref:rate-feed-service-validation-report',
      resolutionActions: ['Manual override', 'Re-ingest', 'Exclude row'],
    },
    {
      rowRef: 'row-ref:feed-fixture-077',
      fieldName: 'productRef',
      severity: 'WARNING',
      blockerCode: 'INVALID_PRODUCT',
      sourceReference: 'source-ref:rate-feed-batch/row/77',
      resolutionState: 'RE_INGESTED',
      rowDataRefs: ['row-data-ref:fixture-077'],
      expectedRef: 'expected-ref:product-catalog-mapping',
      actualRef: 'actual-ref:source-product-ref',
      remediationRef: 'remediation-ref:integration-service-mapping',
      resolutionActions: ['View audit refs'],
    },
  ],
  sourceReferences: ['rate-feed-service:ops-view-fixture', 'integration-service:feed-adapter-refs', 'audit-replay-service:rate-feed-replay'],
  replayEvidence: {
    selectedRunId: 'run-ref:feed-fixture-001',
    runs: [
      { runId: 'run-ref:feed-fixture-001', feedName: 'Primary investor feed fixture', runDateRef: 'date-ref:feed-fixture-run', versionRefs: ['version-ref:rate-feed-contract-v1'] },
      { runId: 'run-ref:feed-fixture-replay', feedName: 'Primary investor feed replay fixture', runDateRef: 'date-ref:feed-fixture-replay', versionRefs: ['version-ref:rate-feed-contract-v1'] },
    ],
    diffs: [
      { diffId: 'diff-ref:row-042', changeType: 'MODIFIED', rowRef: 'row-ref:feed-fixture-042', fieldName: 'noteRateRef', originalRef: 'original-ref:source-missing', replayRef: 'replay-ref:blocked-until-source-fix', sourceRef: 'audit-ref:replay-row-042' },
      { diffId: 'diff-ref:row-077', changeType: 'ADDED', rowRef: 'row-ref:feed-fixture-077', fieldName: 'productRef', originalRef: 'original-ref:no-product-mapping', replayRef: 'replay-ref:integration-mapping-supplied', sourceRef: 'audit-ref:replay-row-077' },
    ],
    missingDependencyBlockers: ['dependency-ref:live-export-contract-unavailable'],
    versionRefs: ['version-ref:rate-feed-ops-fixture', 'version-ref:replay-contract-fixture'],
    exportAvailable: false,
    exportRef: 'export-ref:blocked-until-live-service',
  },
  actionsDisabled: true,
  fallbackReason: 'Connected rate-feed-service, integration-service, live export, Storybook, and E2E runtime are not available in this local lane; UI renders backend-owned refs only.',
  uiTraceId: 'rf-s18-local-trace',
  events: ['event-ref:rate-feed-ops-opened', 'event-ref:replay-viewed'],
};

export const blockedRateFeedOperationsFixture: RateFeedOperationsView = {
  ...rateFeedOperationsFixture,
  dependencyStatus: 'BLOCKED_UPSTREAM_CONTRACT_REQUIRED',
  feedHealth: undefined,
  workflowSteps: [],
  rowBlockers: [],
  replayEvidence: [],
  actionsDisabled: true,
  fallbackReason: 'Rate-feed-service operations contract is unavailable; no local feed adapter or pricing rule logic is synthesized.',
};
