import type { ComplianceEvidenceRegistryView } from '../../lib/api/complianceEvidence';

export const complianceEvidenceFixture: ComplianceEvidenceRegistryView = {
  tenantContext: 'ui-preview-tenant',
  dependencyStatus: 'READY_WITH_FIXTURE_EVIDENCE',
  uiTraceId: 'compliance-evidence-s28-local-trace',
  events: ['artifact-export', 'decision-view', 'privacy-request-process', 'security-acknowledge'],
  fallbackReason: 'Local fixture mirrors configured compliance-service evidence shape for UI validation only.',
  artifacts: [
    {
      artifactId: 'artifact-registry-001',
      path: '/compliance/evidence/artifacts/artifact-registry-001',
      artifactType: 'DISCLOSURE_PACKAGE',
      owner: 'compliance-ops',
      retentionClass: 'REGULATORY_7YR',
      relatedModule: 'quote-detail',
      version: 'v2026-06-fixture',
      hash: 'hash-fixture-artifact-001',
      traceId: 'trace-compliance-artifact-001',
      policyVersion: 'policy-version-ref-001',
      policyDigest: 'policy-digest-ref-001',
      jurisdictionCode: 'jurisdiction-configured-ref',
      continuityStatus: 'CONTINUOUS',
      moduleLinks: ['/quote/run-fixture/detail', '/audit/replay'],
      progressionBlocked: true,
      blockers: ['LEGAL_HOLD_ACTIVE'],
    },
  ],
  decisions: [
    {
      decisionId: 'decision-fixture-001',
      reasonCode: 'DISCLOSURE_REVIEW_REQUIRED',
      humanText: 'Review disclosure artifact references before export.',
      jurisdictionCode: 'jurisdiction-configured-ref',
      reasonTiers: ['COMPLIANCE', 'DISCLOSURE'],
      exportBlocked: true,
      disclosureArtifactRef: 'artifact-registry-001',
    },
  ],
  advisoryReviews: [
    {
      reviewId: 'review-fixture-001',
      reviewType: 'FAIR_LENDING',
      subjectRef: 'quote-option-contract-required',
      status: 'PENDING_REVIEW',
      reasonCodes: ['MODEL_ADVISORY_EVIDENCE_REQUIRED'],
      auditSnapshotRefs: ['audit-snapshot-fixture-001'],
      regulatoryApprovalState: 'APPROVAL_REQUIRED',
      exportRefs: ['export-review-fixture-001'],
      blockedByConfiguration: true,
      configurationGaps: ['fair-lending-jurisdiction-policy-ref-required'],
    },
  ],
  fairLendingMonitoring: [
    {
      drilldownId: 'fair-lending-drilldown-001',
      dimensions: ['race', 'ethnicity', 'gender', 'age'],
      redacted: true,
      redactionState: 'PARTIAL',
      evidenceRefs: ['fair-lending-evidence-ref-001'],
      blockers: ['REDACTION_PROFILE_REQUIRED'],
    },
  ],
  privacyRequests: [
    {
      requestId: 'privacy-request-001',
      borrowerRef: 'borrower-ref-redacted',
      requestedScope: 'FULL_EXPORT',
      identityStatus: 'VERIFYING_IDENTITY',
      slaState: 'BREACHED',
      consentAuditRef: 'consent-audit-ref-001',
      blockers: ['IDENTITY_VERIFICATION_REQUIRED'],
    },
  ],
  securityEvents: [
    {
      eventId: 'security-event-001',
      category: 'EXPORT_ACCESS',
      severity: 'CRITICAL',
      owner: 'security-ops',
      logRecordId: 'log-record-001',
      correlationId: 'correlation-001',
      acknowledged: false,
      blockers: ['SECURITY_ACK_REQUIRED'],
    },
  ],
  alerts: [
    {
      alertId: 'alert-fixture-001',
      severity: 'HIGH',
      alertClass: 'CONFIG_GAP',
      triggerType: 'MISSING_POLICY_REFERENCE',
      routeTarget: '/admin/governance',
      acknowledged: false,
      blockers: ['GOVERNANCE_REMEDIATION_REQUIRED'],
    },
  ],
  retentionControls: [
    {
      ruleId: 'retention-rule-001',
      retentionClass: 'LEGAL_HOLD_INDEFINITE',
      retentionWindow: 'window-configured-by-service',
      legalHoldActive: true,
      deletionGateReason: 'LEGAL_HOLD_ACTIVE',
      backupEvidence: 'backup-evidence-ref-001',
    },
  ],
  configurationGaps: ['fair-lending-jurisdiction-policy-ref-required', 'privacy-export-redaction-profile-required'],
};

export const emptyComplianceEvidenceFixture: ComplianceEvidenceRegistryView = {
  ...complianceEvidenceFixture,
  dependencyStatus: 'READY_EMPTY',
  fallbackReason: '',
  artifacts: [],
  decisions: [],
  advisoryReviews: [],
  fairLendingMonitoring: [],
  privacyRequests: [],
  securityEvents: [],
  alerts: [],
  retentionControls: [],
  configurationGaps: [],
};
