import type { ExceptionConcessionWorkbenchView } from '../../lib/api/exceptionConcessions';

export const exceptionConcessionsFixture: ExceptionConcessionWorkbenchView = {
  tenantContext: 'tenant-fixture',
  dependencyStatus: 'CONFIGURED_REFS_SUPPLIED',
  status: 'READY_WITH_BACKEND_EVIDENCE',
  sections: [
    {
      sectionId: 'concession-request',
      label: 'Concession Request',
      status: 'READY',
      backendRefs: ['exception-service:request-workflow:v1'],
      auditRefs: ['audit:concession-request-fixture'],
      summary: 'Request, review, approval, and audit refs supplied by exception-service.',
    },
    {
      sectionId: 'authority-matrix',
      label: 'Authority Matrix',
      status: 'READY',
      backendRefs: ['governance-service:authority-matrix:v1'],
      auditRefs: ['audit:authority-matrix-fixture'],
      summary: 'Role and limit refs are displayed without local authority evaluation.',
    },
  ],
  concessionRequests: [
    {
      requestId: 'concession-req-fixture-001',
      type: 'PRICE_CONCESSION',
      status: 'IN_REVIEW',
      requestorRef: 'actor:pricing-manager-fixture',
      quoteRef: 'quote:exception-fixture-001',
      impactRef: 'impact-ref:backend-owned-001',
      createdRef: 'time-ref:request-created-001',
      assignedApproverRef: 'approver-ref:capital-markets-queue',
      slaRef: 'sla-ref:configured-response-target',
      allowedActions: ['View', 'Approve', 'Reject', 'Request Info', 'Withdraw'],
      auditRefs: ['audit:concession-request-fixture'],
    },
  ],
  eligibilityExceptions: [
    {
      exceptionId: 'elig-exception-fixture-001',
      ruleCodeRef: 'rule-ref:eligibility-minimum-config',
      quoteRef: 'quote:exception-fixture-001',
      borrowerFactRef: 'fact-ref:borrower-credit-source',
      standardValueRef: 'standard-value-ref:configured-rule',
      exceptionValueRef: 'exception-value-ref:requested-override',
      overrideType: 'HARD',
      status: 'SUBMITTED',
      approverRef: 'approver-ref:executive-queue',
      expirationRef: 'expiration-ref:backend-owned',
      renewalWorkflowRef: 'renewal-ref:exception-service',
      auditRefs: ['audit:eligibility-exception-fixture'],
    },
  ],
  authorityMatrix: [
    {
      roleRef: 'role-ref:pricing-director',
      exceptionTypeRef: 'exception-type-ref:price-concession',
      limitRef: 'limit-ref:governance-config-owned',
      escalationPathRef: 'escalation-ref:configured-path',
      governanceConfigRef: 'governance-config-ref:authority-matrix',
      auditRefs: ['audit:authority-fixture'],
    },
  ],
  manualPriceMutationGuard: {
    commitDisabled: true,
    decision: 'BLOCKED_BY_EXCEPTION_POLICY_REF',
    reasonCodes: ['reason-ref:manual-price-guard-required'],
    escalationPath: 'escalation-ref:manual-price-override',
    auditRef: 'audit:price-guard-fixture',
    replayHash: 'replay-hash-price-guard-fixture',
  },
  priceGuardAttempts: [
    {
      attemptId: 'price-guard-attempt-fixture-001',
      quoteRef: 'quote:exception-fixture-001',
      decision: 'BLOCKED',
      reasonCodes: ['reason-ref:missing-approval'],
      auditRef: 'audit:price-guard-attempt-fixture',
      replayHash: 'replay-hash-price-guard-attempt-fixture',
    },
  ],
  riskEvents: [
    {
      eventId: 'risk-event-fixture-001',
      type: 'COMPLIANCE',
      severity: 'HIGH',
      quoteRef: 'quote:exception-fixture-001',
      detectedAtRef: 'time-ref:risk-detected-001',
      status: 'OPEN',
      ownerRef: 'owner-ref:compliance-queue',
      alertRefs: ['alert-ref:configured-channel'],
      actionRefs: ['Acknowledge', 'Investigate', 'Resolve'],
      auditRefs: ['audit:risk-event-fixture'],
    },
  ],
  historyReplayExports: [
    {
      eventId: 'history-event-fixture-001',
      type: 'CONCESSION_REQUEST',
      status: 'RECORDED',
      actorRef: 'actor:pricing-manager-fixture',
      replayHash: 'replay-hash-history-fixture',
      exportRef: 'export-ref:exception-concessions-fixture',
      retentionClassRef: 'retention-ref:legal-config',
      legalHoldRef: 'legal-hold-ref:configured-state',
      auditRefs: ['audit:history-fixture'],
    },
  ],
  crossServiceRefs: ['exception-service:workbench', 'governance-service:authority', 'audit-replay-service:history'],
  versionRefs: ['version-ref:exception-workbench-fixture'],
  auditRefs: ['audit:exception-workbench-fixture'],
  blockers: [],
  replayHash: 'replay-hash-exception-workbench-fixture',
  exportManifestRef: 'export-manifest:exception-concessions-fixture',
  uiTraceId: 'trace:exception-concessions-fixture',
  events: ['event-ref:exception-workbench-viewed'],
  fallbackReason: 'Connected exception-service supplied fixture refs.',
};

export const blockedExceptionConcessionsFixture: ExceptionConcessionWorkbenchView = {
  ...exceptionConcessionsFixture,
  status: 'BLOCKED_UPSTREAM_CONTRACT_REQUIRED',
  concessionRequests: [],
  eligibilityExceptions: [],
  authorityMatrix: [],
  priceGuardAttempts: [],
  riskEvents: [],
  historyReplayExports: [],
  blockers: ['exception-service workbench contract unavailable'],
  fallbackReason: 'Exception-service, Storybook, and E2E runtime are not available in this local lane.',
};
