import type { OfferComparisonView } from '../../lib/api/offers';

export const deterministicOfferComparison: OfferComparisonView = {
  runId: 'run-preview-001',
  status: 'READY_WITH_FIXTURE_DATA',
  selectedOfferId: null,
  commitBlocked: false,
  sortOptions: ['rank', 'rate', 'apr', 'payment', 'confidence', 'rankScore'],
  fallbackReason: null,
  requiredFacts: [],
  backendRefs: ['quote-service:fixture-unavailable', 'pricing-service:fixture-unavailable'],
  uiTraceId: 'pii-24-s10-local-fixture',
  events: ['fixture:offer-comparison-rendered'],
  offers: [
    {
      offerId: 'offer-a',
      rank: 1,
      productLabel: 'Conventional 30 year fixed',
      productFamily: 'Conventional',
      investor: 'Investor A',
      rate: 6.5,
      price: 99.934,
      apr: 6.74,
      payment: 2104,
      confidence: 96,
      rankScore: 98,
      lockPeriodDays: 30,
      eligibilityStatus: 'Eligible',
      rationaleChips: ['Backend rank 1', 'PRICE_UNAVAILABLE guarded fallback'],
      scenarioFlags: ['CASH_OUT'],
      explanationStatus: 'AVAILABLE',
      explanationSections: ['Pricing summary', 'Eligibility refs'],
      upstreamRefs: ['quote-service:offers'],
      lockEligibilityRefs: ['eligibility-service:lock-ready'],
      snapshotRefs: ['snapshot:offer-a'],
      auditIds: ['audit:offer-a'],
      sourceLabel: 'LoanHouse capture',
      sourceRefs: ['schemaVersion:loanhouse-product-records-v1', 'source_url:https://lhposb2bbff1prod.loanhouse.us/api/v1/no-oauth/quickpricer/get-generic-quote-summary'],
      sourceScenarioId: 'scenario-fixture',
      scenarioVersion: 1,
    },
    {
      offerId: 'offer-b',
      rank: 2,
      productLabel: 'FHA fixed',
      productFamily: 'FHA',
      investor: 'Investor B',
      rate: null,
      apr: null,
      payment: null,
      confidence: 72,
      rankScore: 81,
      lockPeriodDays: 45,
      eligibilityStatus: 'Needs facts',
      rationaleChips: ['PRICE_UNAVAILABLE', 'Backend requires missing facts'],
      scenarioFlags: ['MI_LTV_80'],
      explanationStatus: 'BLOCKED',
      commitBlocked: true,
      requiredFacts: ['pricing-service quote price', 'eligibility lock facts'],
      upstreamRefs: ['pricing-service:missing-price'],
      lockEligibilityRefs: [],
      snapshotRefs: ['snapshot:offer-b'],
      auditIds: ['audit:offer-b'],
      sourceScenarioId: 'scenario-fixture',
      scenarioVersion: 1,
    },
  ],
};
