upstream pricing_bff {
  server pricing-bff.wcpe-dev.svc.cluster.local:8080;
  keepalive 32;
}

server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://pricing_bff;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $http_host;
    proxy_set_header Origin "";
    proxy_set_header Access-Control-Request-Method "";
    proxy_set_header Access-Control-Request-Headers "";
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
