import type { DriftMonitoringView } from './types';

export const blockedDriftMonitoringView: DriftMonitoringView = {
  tenantContext: 'ui-preview-tenant',
  modelVersion: 'model-version-ref-required',
  modelVersionStatus: 'Not in production',
  timeRange: '24h',
  dependencyStatus: 'ML_ADVISORY_DRIFT_CONTRACT_NOT_CONFIGURED',
  uiTraceId: 'drift-s27-local-trace',
  fallbackReason: 'Configured ML advisory drift APIs are unavailable; fallback records story-approved thresholds, blocked actions, and evidence refs only.',
  featureDrift: [
    {
      featureName: 'loan-to-value-feature-ref',
      psi: 0.08,
      ksStatistic: 0.04,
      pValue: 0.08,
      histogram: ['reference: low-mid-high', 'current: low-mid-high'],
      status: 'STABLE',
      evidenceRef: 'feature-drift-evidence-ref-required',
    },
    {
      featureName: 'credit-band-feature-ref',
      psi: 0.16,
      ksStatistic: 0.11,
      pValue: 0.04,
      histogram: ['reference: low-mid-high', 'current: low-mid-high'],
      status: 'WARNING',
      evidenceRef: 'ks-test-evidence-ref-required',
    },
    {
      featureName: 'channel-feature-ref',
      psi: 0.24,
      ksStatistic: 0.19,
      pValue: 0.02,
      histogram: ['reference: low-mid-high', 'current: low-mid-high'],
      status: 'CRITICAL',
      evidenceRef: 'critical-drift-evidence-ref-required',
    },
  ],
  predictionDrift: {
    meanShiftStdDev: 2.6,
    meanShiftStatus: 'WARNING',
    distributionShift: 'Wasserstein distance supplied by prediction drift API',
    accuracy: null,
    accuracyState: 'Insufficient labels',
    calibrationRef: 'calibration-plot-ref-required',
  },
  populationStability: {
    psiOverTime: [
      { bucket: '1h', psi: 0.06 },
      { bucket: '6h', psi: 0.12 },
      { bucket: '24h', psi: 0.21 },
    ],
    cohorts: [
      { cohort: 'channel', psi: 0.18, topFeature: 'channel-feature-ref', status: 'WARNING' },
      { cohort: 'product', psi: 0.07, topFeature: 'product-feature-ref', status: 'STABLE' },
      { cohort: 'region', psi: 0.23, topFeature: 'region-feature-ref', status: 'CRITICAL' },
    ],
  },
  alerts: [
    {
      alertId: 'drift-alert-001',
      rule: 'PSI > threshold',
      severity: 'CRITICAL',
      modelVersion: 'model-version-ref-required',
      metric: 'population stability index',
      triggeredAt: 'timestamp-supplied-by-service',
      status: 'ACTIVE',
      owner: 'model-operations-owner-ref',
      currentValue: '0.24 PSI',
      threshold: '> 0.2',
      history: ['UNACKNOWLEDGED > 15 min -> team lead', 'CRITICAL unacknowledged > 5 min -> page on-call'],
    },
    {
      alertId: 'drift-alert-002',
      rule: 'KS p-value < 0.05',
      severity: 'WARNING',
      modelVersion: 'model-version-ref-required',
      metric: 'credit-band-feature-ref',
      triggeredAt: 'timestamp-supplied-by-service',
      status: 'ACKNOWLEDGED',
      owner: 'data-science-owner-ref',
      currentValue: 'p-value 0.04',
      threshold: '< 0.05',
      history: ['UNRESOLVED > 1 hour -> manager'],
    },
  ],
  investigation: {
    selectedAlertId: 'drift-alert-001',
    rootCauseNotes: ['5 Whys notes require analyst entry', 'Fishbone causes: data quality, model version, population mix, operational process'],
    dataQualityChecks: ['missing values check', 'schema changes check', 'outlier rates check'],
    featureAttribution: ['SHAP values supplied by drift investigation API'],
    remediationPlan: [
      { action: 'Review population stability evidence', owner: 'model-operations-owner-ref', dueDate: 'due-date-ref-required', status: 'OPEN' },
      { action: 'Prepare monitoring threshold review', owner: 'risk-reviewer-ref', dueDate: 'due-date-ref-required', status: 'PLANNED' },
    ],
    exportEvidenceRef: 'drift-investigation-export-ref-required',
    replayHashRef: 'replay-hash-ref-required',
  },
  events: ['DriftMonitoringOpened', 'DriftInvestigationExportPrepared', 'DriftAlertAcknowledgementCaptured'],
};
