plugins {
  id 'java'
  id 'org.springframework.boot' version '3.3.5'
  id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.wcpe'
version = '0.1.0'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  implementation 'org.springframework.boot:spring-boot-starter-jdbc'
  implementation 'org.flywaydb:flyway-core'
  runtimeOnly 'org.flywaydb:flyway-database-postgresql'
  runtimeOnly 'org.postgresql:postgresql'
  testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

tasks.named('bootJar') {
  archiveFileName = 'lock-service-0.1.0.jar'
}

tasks.named('test') {
  useJUnitPlatform()
}
