import type { QuoteDetailView } from '../../lib/api/offers';

export const deterministicQuoteDetail: QuoteDetailView = {
  tenantContext: 'tenant-fixture',
  runId: 'run-preview-001',
  offerId: 'offer-a',
  status: 'READY',
  summary: {
    offerId: 'offer-a',
    rank: 1,
    productLabel: 'Conventional 30 year fixed',
    productFamily: 'Conventional',
    investor: 'Investor A',
    rate: '6.500%',
    apr: '6.740%',
    payment: '$2,104',
    confidence: '96',
    rankScore: '98',
    lockPeriodDays: 30,
    eligibilityStatus: 'Eligible',
    rationaleChips: ['Backend rank 1', 'Quote-service selected option'],
    scenarioFlags: ['CASH_OUT'],
    explanationStatus: 'AVAILABLE',
    explanationSections: ['Adjustment count: backend supplied 3', 'Margin summary: backend supplied branch and LO refs'],
    upstreamRefs: ['quote-service:offers', 'pricing-service:waterfall', 'adjustment-service:ledger'],
    lockEligibilityRefs: ['eligibility-service:lock-ready'],
    snapshotRefs: ['snapshot:offer-a'],
    auditIds: ['audit:offer-a'],
    sourceScenarioId: 'scenario-fixture',
    scenarioVersion: 1,
  },
  explanation: {
    runId: 'run-preview-001',
    offerId: 'offer-a',
    status: 'AVAILABLE',
    rationaleLines: ['Selected by backend rank service.', 'Pricing evidence is rendered from the returned waterfall ledger.'],
    scenarioFlags: ['CASH_OUT'],
    upstreamRefs: ['adjustment-service:adj-001', 'margin-service:margin-branch-001', 'eligibility-service:elig-001'],
    snapshotRefs: ['snapshot:offer-a'],
    auditIds: ['audit:offer-a'],
    explanationSections: ['Base grid selected by pricing-service.', 'Final price trace uses backend rounding refs.'],
    commitBlocked: false,
    message: 'Backend explanation available.',
    uiTraceId: 'pii-24-s11-explain-fixture',
  },
  waterfall: {
    tenantContext: 'tenant-fixture',
    runId: 'run-preview-001',
    status: 'READY',
    restrictedValuesVisible: false,
    dependencyStatus: 'fixture-backed',
    baseSelection: {
      selectionId: 'base-selection-001',
      gridVersionRef: 'grid:v2026-06-quote-fixture',
      selectedNoteRate: { value: '6.500%', redacted: false, reason: null },
      basePrice: { value: '101.125', redacted: false, reason: null },
      ledgerSteps: ['base-grid', 'adjustments', 'margin', 'rounding'],
    },
    finalPrice: {
      finalPriceId: 'final-price-001',
      roundedFinalPrice: { value: '100.875', redacted: false, reason: null },
      adjustmentRefs: ['adjustment-service:adj-001'],
      roundingTraceRefs: ['pricing-service:rounding-trace-001'],
      ledger: [
        {
          ordinal: 1,
          step: 'Base grid',
          inputValue: { value: '6.500%', redacted: false, reason: null },
          operation: 'BACKEND_BASE_SELECTION',
          outputValue: { value: '101.125', redacted: false, reason: null },
          configRef: 'grid:v2026-06-quote-fixture',
          reasonCode: 'BASE_GRID',
          roundingMode: null,
        },
        {
          ordinal: 2,
          step: 'Compensation adjustment',
          inputValue: { value: null, redacted: true, reason: 'COMPENSATION_CONFIDENTIAL' },
          operation: 'BACKEND_ADJUSTMENT',
          outputValue: { value: null, redacted: true, reason: 'COMPENSATION_CONFIDENTIAL' },
          configRef: 'adjustment-service:adj-001',
          reasonCode: 'REDACTED_COMPENSATION',
          roundingMode: null,
        },
        {
          ordinal: 3,
          step: 'Final rounding',
          inputValue: { value: '100.878', redacted: false, reason: null },
          operation: 'BACKEND_ROUNDING',
          outputValue: { value: '100.875', redacted: false, reason: null },
          configRef: 'pricing-service:rounding-trace-001',
          reasonCode: 'ROUNDING_TRACE',
          roundingMode: 'nearest-eighth-from-backend',
        },
      ],
    },
    blockers: [],
    versionRefs: ['pricing-config:v2026-06', 'margin-config:v2026-06'],
    auditRefs: ['audit:offer-a', 'audit:waterfall-001'],
    replayHash: 'replay-hash-offer-a',
    versionGraphHash: 'version-graph-hash-offer-a',
    resultHash: 'result-hash-offer-a',
    evidenceHash: 'evidence-hash-offer-a',
    uiTraceId: 'pii-24-s11-waterfall-fixture',
    events: ['fixture:quote-detail-waterfall-rendered'],
    fallbackReason: '',
  },
  panels: [
    { panelId: 'summary', label: 'Summary', status: 'READY', fields: ['productLabel', 'investor', 'rate', 'apr', 'payment', 'rank'], backendRefs: ['quote-service:offers'], blockers: [] },
    { panelId: 'waterfall', label: 'Waterfall', status: 'READY', fields: ['baseSelection', 'ledger', 'finalPrice'], backendRefs: ['pricing-service:waterfall'], blockers: [] },
    { panelId: 'compliance', label: 'Compliance', status: 'READY', fields: ['complianceFlags'], backendRefs: ['compliance-service:evidence'], blockers: [] },
    { panelId: 'audit', label: 'Audit / Replay', status: 'READY', fields: ['auditRefs', 'replayHash', 'evidenceHash'], backendRefs: ['audit-replay-service:package'], blockers: [] },
  ],
  redactions: [
    { fieldPath: 'waterfall.finalPrice.ledger[1].inputValue', state: 'REDACTED', reason: 'COMPENSATION_CONFIDENTIAL', auditRef: 'audit:redaction-001' },
    { fieldPath: 'waterfall.finalPrice.ledger[1].outputValue', state: 'REDACTED', reason: 'COMPENSATION_CONFIDENTIAL', auditRef: 'audit:redaction-001' },
  ],
  complianceFlags: ['ATR_QM|PASS|Federal|/compliance/evidence/ATR_QM/audit:offer-a', 'HPML|REVIEW|State|/compliance/evidence/HPML/audit:offer-a'],
  auditRefs: ['audit:offer-a', 'audit:waterfall-001'],
  replayHash: 'replay-hash-offer-a',
  evidenceHash: 'evidence-hash-offer-a',
  uiTraceId: 'pii-24-s11-local-fixture',
  events: ['fixture:quote-detail-rendered', 'fixture:redaction-metadata-present'],
  fallbackReason: '',
};
