plugins {
  id 'java'
}

group = 'com.wcpe'
version = '0.1.0'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

dependencies {
  implementation 'org.springframework:spring-web:6.1.14'
  testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
  testImplementation 'com.h2database:h2:2.2.224'
}

tasks.named('test') {
  useJUnitPlatform()
}
