import type { QuoteJourneyMapView } from '../../lib/api/quoteRuns';

export const deterministicQuoteJourneyMap: QuoteJourneyMapView = {
  tenantContext: 'ui-preview-tenant',
  runId: 'run-test',
  status: 'PREVIEW_EVIDENCE',
  dependencyStatus: 'Preview/evidence route uses deterministic local records when BFF journey contracts are not available.',
  blockers: ['Production journey data requires quote-service, pricing-service, lock-service, and audit replay contracts.'],
  serviceContracts: ['scenario-service:draft', 'quote-service:run', 'pricing-service:waterfall', 'lock-service:workflow', 'audit-service:replay'],
  uiTraceId: 'journey-preview-local-trace',
  events: ['preview:journey-map-route', 'preview:evidence-labelled'],
  fallbackReason: 'DETERMINISTIC_PREVIEW_EVIDENCE',
  nodes: [
    {
      nodeId: 'scenario-intake',
      label: 'Scenario intake',
      serviceName: 'scenario-service',
      status: 'VISIBLE_WITH_REFS',
      freshness: { status: 'preview-current', evidenceRef: 'scenario-service:preview-draft', message: 'Borrower and loan facts are represented by deterministic preview references.' },
      evidenceRefs: ['scenario-service:preview-draft', 'quote-run:run-test'],
      blockers: [],
      replayHash: 'replay:journey:scenario-preview',
      downstreamDependencies: ['quote-service', 'pricing-service'],
      drilldownRoute: '/pipeline',
      drilldownRefs: { runId: 'run-test', scenarioRef: 'scenario-preview-001', quoteRef: 'quote-preview-001', lockRef: 'lock-preview-pending', correlationRef: 'journey-preview-correlation' },
    },
    {
      nodeId: 'pricing-waterfall',
      label: 'Pricing waterfall evidence',
      serviceName: 'pricing-service',
      status: 'VISIBLE_WITH_REFS',
      freshness: { status: 'preview-current', evidenceRef: 'pricing-service:waterfall-preview', message: 'Waterfall evidence links to the preview Pricing Waterfall page without local pricing calculation.' },
      evidenceRefs: ['pricing-service:waterfall-preview', 'audit:pricing-preview'],
      blockers: [],
      replayHash: 'replay:journey:pricing-preview',
      downstreamDependencies: ['quote-service', 'audit-service'],
      drilldownRoute: '/pricing/waterfall',
      drilldownRefs: { runId: 'run-test', scenarioRef: 'scenario-preview-001', quoteRef: 'quote-preview-001', lockRef: 'lock-preview-pending', correlationRef: 'journey-preview-correlation' },
    },
    {
      nodeId: 'lock-and-review',
      label: 'Lock and review readiness',
      serviceName: 'lock-service',
      status: 'VISIBLE_WITH_BLOCKERS',
      freshness: { status: 'preview-blocked', evidenceRef: 'lock-service:preview-required', message: 'Lock submission remains a preview node until connected service evidence is available.' },
      evidenceRefs: ['lock-service:preview-required'],
      blockers: ['Connected lock workflow contract required for production evidence.'],
      replayHash: 'replay:journey:lock-preview',
      downstreamDependencies: ['compliance-service', 'partner-integration-service'],
      drilldownRoute: '/quote/run-test/lock',
      drilldownRefs: { runId: 'run-test', scenarioRef: 'scenario-preview-001', quoteRef: 'quote-preview-001', lockRef: 'lock-preview-pending', correlationRef: 'journey-preview-correlation' },
    },
  ],
};
