import type { MarginProfitabilityView } from '../../lib/api/marginProfitability';

export const marginProfitabilityFixture: MarginProfitabilityView = {
  tenantContext: 'tenant-fixture',
  dependencyStatus: 'Connected margin profitability fixture is available for local UI validation.',
  status: 'READY_WITH_BACKEND_REFS',
  compensationDetailsVisible: false,
  sections: [
    {
      sectionId: 'company',
      label: 'Company Margin',
      sourceRef: 'margin-service:company-margin-fixture',
      permissionState: 'VISIBLE',
      displayValue: 'backend-supplied company margin ref',
      evidenceRefs: ['evidence:company-margin-001', 'version:company-margin-policy-fixture'],
      redactions: [],
    },
    {
      sectionId: 'branch',
      label: 'Branch Margin',
      sourceRef: 'margin-service:branch-margin-fixture',
      permissionState: 'REDACTED',
      evidenceRefs: ['evidence:branch-margin-001'],
      redactions: [{ fieldLabel: 'Branch compensation spread', state: 'REDACTED', reason: 'COMPENSATION_CONFIDENTIAL', auditRef: 'audit:branch-redaction-001' }],
    },
    {
      sectionId: 'lo',
      label: 'LO Margin',
      sourceRef: 'compensation-service:lo-plan-ref-fixture',
      permissionState: 'RESTRICTED',
      requestAccessAllowed: true,
      evidenceRefs: ['evidence:lo-margin-001'],
      redactions: [{ fieldLabel: 'LO compensation plan', state: 'RESTRICTED', reason: 'ROLE_REQUIRED', auditRef: 'audit:lo-access-001' }],
    },
    {
      sectionId: 'investor',
      label: 'Investor Margin',
      sourceRef: 'investor-ref:margin-fixture',
      permissionState: 'VISIBLE',
      displayValue: 'backend-supplied investor margin ref',
      evidenceRefs: ['evidence:investor-margin-001'],
      redactions: [],
    },
    {
      sectionId: 'secondary-market',
      label: 'Secondary Market Margin',
      sourceRef: 'secondary-market:margin-fixture',
      permissionState: 'VISIBLE',
      displayValue: 'backend-supplied secondary market ref',
      evidenceRefs: ['evidence:secondary-market-margin-001'],
      redactions: [],
    },
  ],
  floorEvidence: [
    {
      quoteOptionId: 'quote-option-fixture-pass',
      decision: 'PASS',
      decisionCode: 'FLOOR_PASS_BACKEND_REF',
      floorPolicyVersionRef: 'floor-policy:v-fixture',
      thresholdRef: 'threshold-ref:fixture-pass',
      exceptionRouteRef: '/exceptions/concessions?quoteOptionId=quote-option-fixture-pass',
      auditRefs: ['audit:floor-pass-001'],
      displayGuidance: 'Backend floor evidence indicates no exception action for this quote option.',
      thresholdCalculationRef: 'calc-ref:floor-pass-fixture',
      exceptionWorkflowRef: 'workflow-ref:not-required-fixture',
    },
    {
      quoteOptionId: 'quote-option-fixture-fail',
      decision: 'FAIL',
      decisionCode: 'FLOOR_EXCEPTION_REQUIRED_REF',
      floorPolicyVersionRef: 'floor-policy:v-fixture',
      thresholdRef: 'threshold-ref:fixture-fail',
      exceptionRouteRef: '/exceptions/concessions?quoteOptionId=quote-option-fixture-fail',
      auditRefs: ['audit:floor-fail-001'],
      displayGuidance: 'Backend floor evidence requires exception workflow review.',
      thresholdCalculationRef: 'calc-ref:floor-fail-fixture',
      exceptionWorkflowRef: 'workflow-ref:floor-exception-fixture',
    },
    {
      quoteOptionId: 'quote-option-fixture-warn',
      decision: 'WARN',
      decisionCode: 'FLOOR_MONITORING_REF',
      floorPolicyVersionRef: 'floor-policy:v-fixture',
      thresholdRef: 'threshold-ref:fixture-warn',
      exceptionRouteRef: '',
      auditRefs: ['audit:floor-warn-001'],
      displayGuidance: 'Backend floor evidence recommends monitoring.',
      thresholdCalculationRef: 'calc-ref:floor-warn-fixture',
    },
  ],
  approvalStatus: {
    currentVersionRef: 'margin-version:v-fixture',
    status: 'PENDING_APPROVAL',
    allowedActions: ['APPROVE', 'REJECT'],
    snapshotRefs: ['snapshot:margin-approval-001'],
    auditRefs: ['audit:approval-view-001'],
    chain: [
      { role: 'pricing-manager', actorRef: 'user-ref:pricing-manager-fixture', status: 'APPROVED', timestampRef: 'time-ref:approval-step-001', auditRef: 'audit:approval-step-001' },
      { role: 'capital-markets', actorRef: 'user-ref:capital-markets-fixture', status: 'PENDING', timestampRef: 'time-ref:approval-step-002', auditRef: 'audit:approval-step-002' },
    ],
  },
  versionRefs: ['margin-config:v-fixture', 'governance-config:margin-fixture'],
  auditRefs: ['audit:margin-view-001', 'audit:margin-export-001'],
  replayHash: 'replay-hash-margin-profitability-001',
  uiTraceId: 'margin-s16-local-trace',
  correlationRefs: ['correlation:margin-profitability-fixture'],
  events: ['margin-section-expand', 'floor-drilldown', 'approval-affordance', 'evidence-export'],
  fallbackReason: 'Fixture values use backend-shaped strings only; no margin, compensation, floor, price, or profitability calculation is performed locally.',
};

export const blockedMarginProfitabilityFixture: MarginProfitabilityView = {
  ...marginProfitabilityFixture,
  dependencyStatus: 'Margin profitability API is unavailable in the local harness.',
  status: 'BLOCKED',
  sections: [],
  floorEvidence: [],
  approvalStatus: undefined,
  fallbackReason: 'Connected margin-service profitability evidence is required before live rows can render.',
};
